### ISSUE TITLE
subscription is terminated after couple of minutes

### ISSUE THREAD

**Issue by martin8282** [aws-samples/aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4#3]
Hi, I am trying to use your framework in order to perform communication with IOT core. I have tried both apps - win forms and console core, but encountered one problem. If I connect or subscribe it works initially when I send messages from IOT core, but if I stay idle for 5-10 minutes, messages will not go through anymore. I assume it is getting disconnected. Reconnecting is expensive especially if you plan to have 3K to 10K clients. Is there a way to have connection alive?

**Comment by sundarnarasiman** [comment]
> Hi, I am trying to use your framework in order to perform communication with IOT core. I have tried both apps - win forms and console core, but encountered one problem. If I connect or subscribe it works initially when I send messages from IOT core, but if I stay idle for 5-10 minutes, messages will not go through anymore. I assume it is getting disconnected. Reconnecting is expensive especially if you plan to have 3K to 10K clients. Is there a way to have connection alive?



> Hi, I am trying to use your framework in order to perform communication with IOT core. I have tried both apps - win forms and console core, but encountered one problem. If I connect or subscribe it works initially when I send messages from IOT core, but if I stay idle for 5-10 minutes, messages will not go through anymore. I assume it is getting disconnected. Reconnecting is expensive especially if you plan to have 3K to 10K clients. Is there a way to have connection alive?

That's the default behaviour of AWS Iot Core. If you need longer connection, you can try implementing MQTT Persistent sessions.

https://docs.aws.amazon.com/iot/latest/developerguide/mqtt-persistent-sessions.html

**Comment by hussainamir** [comment]
@sundarnarasiman  Dear I am facing same problem, after 2,3 mint my client disconnect from aws iot core mqtt broker by using sigv4 method.
how i can implement mqtt persistent sessions ?
Best Regards:
